#!/usr/bin/env python
"""rcollatz: The Collatz sequence, sometimes called 'the simplest impossible math problem.'"""

def collatz(n):
    """ Returns the collatz value for a number n."""
    if n % 2 == 0: r = n // 2
    else: r = 3 * n + 1
    print(r)
    return r

def rcollatz(n):
    """ Recursively call collatz. """
    r = collatz(n)
    if r == 1:  return n
    return rcollatz(r)
    
rcollatz(3)
